[template.environment]
  FIREBLOG_GRAPHQL_ENDPOINT="https://api.fireblogcms.com/beta/blogset/5f5f73057ac2640018cb0fc7"
  FIREBLOG_BLOG_ID="5e0cc6b2c96420000444d376"
  FIREBLOG_FOLDER_BLOG_ID="5e0cc6b2c96420000444d377"
  SITE_URL="http://localhost:3000"
